# Modelo final

In [1]:
# import libraries
import pandas as pd
import numpy as np

**load data**

In [2]:
results = pd.read_csv('../data/results.csv', sep=',', encoding='utf-8')
y = pd.read_csv('../data/target.csv', sep=',', encoding='utf-8', header=None)
X = pd.read_csv('../data/preds_scaled.csv', sep=',', encoding='utf-8')

**predictors**

In [3]:
X

0         1         2         3         4         5         6  \
0    1.097064 -2.073335  1.269934  0.984375  1.568466  3.283515  2.652874   
1    1.829821 -0.353632  1.685955  1.908708 -0.826962 -0.487072 -0.023846   
2    1.579888  0.456187  1.566503  1.558884  0.942210  1.052926  1.363478   
3   -0.768909  0.253732 -0.592687 -0.764464  3.283553  3.402909  1.915897   
4    1.750297 -1.151816  1.776573  1.826229  0.280372  0.539340  1.371011   
..        ...       ...       ...       ...       ...       ...       ...   
564  2.110995  0.721473  2.060786  2.343856  1.041842  0.219060  1.947285   
565  1.704854  2.085134  1.615931  1.723842  0.102458 -0.017833  0.693043   
566  0.702284  2.045574  0.672676  0.577953 -0.840484 -0.038680  0.046588   
567  1.838341  2.336457  1.982524  1.735218  1.525767  3.272144  3.296944   
568 -1.808401  1.221792 -1.814389 -1.347789 -3.112085 -1.150752 -1.114873   

            7         8         9  ...        20        21        22  \
0    2.532475  2.217515  2.255747  ...  1.886690 -1.359293  2.303601   
1    0.548144  0.001392 -0.868652  ...  1.805927 -0.369203  1.535126   
2    2.037231  0.939685 -0.398008  ...  1.511870 -0.023974  1.347475   
3    1.451707  2.867383  4.910919  ... -0.281464  0.133984 -0.249939   
4    1.428493 -0.009560 -0.562450  ...  1.298575 -1.466770  1.338539   
..        ...       ...       ...  ...       ...       ...       ...   
564  2.320965 -0.312589 -0.931027  ...  1.901185  0.117700  1.752563   
565  1.263669 -0.217664 -1.058611  ...  1.536720  2.047399  1.421940   
566  0.105777 -0.809117 -0.895587  ...  0.561361  1.374854  0.579001   
567  2.658866  2.137194  1.043695  ...  1.961239  2.237926  2.303601   
568 -1.261820 -0.820070 -0.561032  ... -1.410893  0.764190 -1.432735   

           23        24        25        26        27        28        29  
0    2.001237  1.307686  2.616665  2.109526  2.296076  2.750622  1.937015  
1    1.890489 -0.375612 -0.430444 -0.146749  1.087084 -0.243890  0.281190  
2    1.456285  0.527407  1.082932  0.854974  1.955000  1.152255  0.201391  
3   -0.550021  3.394275  3.893397  1.989588  2.175786  6.046041  4.935010  
4    1.220724  0.220556 -0.313395  0.613179  0.729259 -0.868353 -0.397100  
..        ...       ...       ...       ...       ...       ...       ...  
564  2.015301  0.378365 -0.273318  0.664512  1.629151 -1.360158 -0.709091  
565  1.494959 -0.691230 -0.394820  0.236573  0.733827 -0.531855 -0.973978  
566  0.427906 -0.809587  0.350735  0.326767  0.414069 -1.104549 -0.318409  
567  1.653171  1.430427  3.904848  3.197605  2.289985  1.919083  2.219635  
568 -1.075813 -1.859019 -1.207552 -1.305831 -1.745063 -0.048138 -0.751207  

[569 rows x 30 columns]

In [4]:
X.shape

(569, 30)

**target**

In [5]:
y

0
0    1
1    1
2    1
3    1
4    1
..  ..
564  1
565  1
566  1
567  1
568  0

[569 rows x 1 columns]

In [6]:
y.values.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [7]:
X = X.values
y = y.values.flatten()

## **results**

In [8]:
results.set_index('modelo')

previsores  acuracia_teste  acuracia_treino  \
modelo                                                                 
Naive Bayes                original           92.40            94.22   
Naive Bayes             padronizado           91.23            94.22   
Support Vector Machine     original           92.40            90.45   
Support Vector Machine  padronizado           97.66            98.24   
Logistic Regression        original           95.91            94.22   
Logistic Regression     padronizado           97.66            98.99   
KNN                        original           94.74            93.97   
KNN                     padronizado           95.91            96.98   
Árvores de decisão         original           91.23           100.00   
Árvores de decisão      padronizado           91.23           100.00   
Random Forest              original           95.91           100.00   
Random Forest           padronizado           95.91           100.00   
Gradient Boosting          original           97.66           100.00   
Gradient Boosting       padronizado           97.66           100.00   
XGBoosting                 original           97.66           100.00   
XGBoosting              padronizado           97.66           100.00   

                        acuracia_cv  precision  recall  f1_score  \
modelo                                                             
Naive Bayes                   93.83      92.43   92.40     92.41   
Naive Bayes                   93.13      91.37   91.23     91.27   
Support Vector Machine        91.58      92.92   92.40     92.22   
Support Vector Machine        97.89      97.67   97.66     97.65   
Logistic Regression           93.15      96.01   95.91     95.93   
Logistic Regression           97.89      97.67   97.66     97.65   
KNN                           92.98      94.76   94.74     94.75   
KNN                           97.01      96.01   95.91     95.87   
Árvores de decisão            92.08      91.71   91.23     91.31   
Árvores de decisão            92.08      91.71   91.23     91.31   
Random Forest                 96.31      95.93   95.91     95.91   
Random Forest                 96.31      95.93   95.91     95.91   
Gradient Boosting             96.66      97.66   97.66     97.66   
Gradient Boosting             96.66      97.66   97.66     97.66   
XGBoosting                    97.19      97.66   97.66     97.66   
XGBoosting                    97.19      97.66   97.66     97.66   

                             matriz_confusao  dif_acuracia_treino_teste  
modelo                                                                   
Naive Bayes              [[101, 7], [6, 57]]                       1.82  
Naive Bayes               [[99, 9], [6, 57]]                       2.99  
Support Vector Machine  [[107, 1], [12, 51]]                      -1.95  
Support Vector Machine   [[107, 1], [3, 60]]                       0.58  
Logistic Regression      [[103, 5], [2, 61]]                      -1.69  
Logistic Regression      [[107, 1], [3, 60]]                       1.33  
KNN                      [[103, 5], [4, 59]]                      -0.77  
KNN                      [[107, 1], [6, 57]]                       1.07  
Árvores de decisão       [[97, 11], [4, 59]]                       8.77  
Árvores de decisão       [[97, 11], [4, 59]]                       8.77  
Random Forest            [[104, 4], [3, 60]]                       4.09  
Random Forest            [[104, 4], [3, 60]]                       4.09  
Gradient Boosting        [[106, 2], [2, 61]]                       2.34  
Gradient Boosting        [[106, 2], [2, 61]]                       2.34  
XGBoosting               [[106, 2], [2, 61]]                       2.34  
XGBoosting               [[106, 2], [2, 61]]                       2.34

**top 3 by accuracy**

In [9]:
results.nlargest(3, 'acuracia_teste')

modelo   previsores  acuracia_teste  acuracia_treino  \
3   Support Vector Machine  padronizado           97.66            98.24   
5      Logistic Regression  padronizado           97.66            98.99   
12       Gradient Boosting     original           97.66           100.00   

    acuracia_cv  precision  recall  f1_score      matriz_confusao  \
3         97.89      97.67   97.66     97.65  [[107, 1], [3, 60]]   
5         97.89      97.67   97.66     97.65  [[107, 1], [3, 60]]   
12        96.66      97.66   97.66     97.66  [[106, 2], [2, 61]]   

    dif_acuracia_treino_teste  
3                        0.58  
5                        1.33  
12                       2.34

**top 3 cross validation accuracy**

In [10]:
results.nlargest(3, 'acuracia_cv')

modelo   previsores  acuracia_teste  acuracia_treino  \
3   Support Vector Machine  padronizado           97.66            98.24   
5      Logistic Regression  padronizado           97.66            98.99   
14              XGBoosting     original           97.66           100.00   

    acuracia_cv  precision  recall  f1_score      matriz_confusao  \
3         97.89      97.67   97.66     97.65  [[107, 1], [3, 60]]   
5         97.89      97.67   97.66     97.65  [[107, 1], [3, 60]]   
14        97.19      97.66   97.66     97.66  [[106, 2], [2, 61]]   

    dif_acuracia_treino_teste  
3                        0.58  
5                        1.33  
14                       2.34

**top 3 f1 score**

In [11]:
results.nlargest(3, 'f1_score')

modelo   previsores  acuracia_teste  acuracia_treino  \
12  Gradient Boosting     original           97.66            100.0   
13  Gradient Boosting  padronizado           97.66            100.0   
14         XGBoosting     original           97.66            100.0   

    acuracia_cv  precision  recall  f1_score      matriz_confusao  \
12        96.66      97.66   97.66     97.66  [[106, 2], [2, 61]]   
13        96.66      97.66   97.66     97.66  [[106, 2], [2, 61]]   
14        97.19      97.66   97.66     97.66  [[106, 2], [2, 61]]   

    dif_acuracia_treino_teste  
12                       2.34  
13                       2.34  
14                       2.34

## hiperparameters

In [12]:
from sklearn.model_selection import GridSearchCV, train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics import roc_auc_score, classification_report, accuracy_score, confusion_matrix

import warnings
warnings.filterwarnings('ignore')

In [13]:
# train test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

**1 - SVM**

In [14]:
from sklearn.svm import SVC

In [15]:
svm = SVC(random_state=0)

In [16]:
param_grid_svm = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['rbf', 'poly', 'sigmoid'],
    'gamma': ['scale', 'auto', 0.1, 1],
    'degree': [2, 3, 4]  
}

In [18]:
grid_search_svm = GridSearchCV(svm, param_grid_svm, cv=5, scoring='roc_auc')
grid_search_svm.fit(X_train, y_train)

print("Melhores parâmetros:", grid_search_svm.best_params_)
print("Melhor pontuação:%.2f%%" % (grid_search_svm.best_score_ * 100.0))

Melhores parâmetros: {'C': 1, 'degree': 2, 'gamma': 'scale', 'kernel': 'rbf'}
Melhor pontuação:99.45%


In [19]:
best_model_svm = grid_search_svm.best_estimator_
y_pred_svm = best_model_svm.predict(X_test)

In [20]:
print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98       108
           1       0.95      0.97      0.96        63

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171



In [21]:
best_model_svm.score(X_train, y_train)

0.9874371859296482

In [22]:
accuracy_score(y_test, y_pred_svm)

0.9707602339181286

In [23]:
confusion_matrix(y_test, y_pred_svm)

array([[105,   3],
       [  2,  61]])

**2 - Log Regression**

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
lr = LogisticRegression(random_state=0)

In [26]:
param_grid_lr = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2', 'elasticnet'],
    'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
    'multi_class': ['ovr', 'multinomial']
}

In [28]:
grid_search_lr = GridSearchCV(lr, param_grid_lr, cv=5, scoring='roc_auc')
grid_search_lr.fit(X_train, y_train)

print("Melhores parâmetros:", grid_search_lr.best_params_)
print("Melhor pontuação:%.2f%%" % (grid_search_lr.best_score_ * 100.0))

Melhores parâmetros: {'C': 1, 'multi_class': 'ovr', 'penalty': 'l2', 'solver': 'sag'}
Melhor pontuação:99.38%


In [31]:
best_model_lr = grid_search_lr.best_estimator_
y_pred_lr = best_model_lr.predict(X_test)

In [32]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       108
           1       0.98      0.98      0.98        63

    accuracy                           0.99       171
   macro avg       0.99      0.99      0.99       171
weighted avg       0.99      0.99      0.99       171



In [34]:
best_model_lr.score(X_train, y_train)

0.9849246231155779

In [35]:
accuracy_score(y_test, y_pred_lr)

0.9883040935672515

In [36]:
confusion_matrix(y_test, y_pred_lr)

array([[107,   1],
       [  1,  62]])

**3 - gradient boosting**

In [37]:
from sklearn.ensemble import GradientBoostingClassifier

In [38]:
gb = GradientBoostingClassifier(random_state=0)

In [39]:
param_grid_gb = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [2, 3, 4],
    'min_samples_split': [2, 4, 6],
    'min_samples_leaf': [1, 2, 3]
}

In [40]:
grid_search_gb = GridSearchCV(gb, param_grid_gb, cv=5, scoring='roc_auc')
grid_search_gb.fit(X_train, y_train)

print("Melhores parâmetros:", grid_search_gb.best_params_)
print("Melhor pontuação:%.2f%%" % (grid_search_gb.best_score_ * 100.0))

Melhores parâmetros: {'learning_rate': 0.05, 'max_depth': 3, 'min_samples_leaf': 3, 'min_samples_split': 2, 'n_estimators': 300}
Melhor pontuação:99.04%


In [43]:
best_model_gb = grid_search_gb.best_estimator_
y_pred_gb = best_model_gb.predict(X_test)

In [44]:
print(classification_report(y_test, y_pred_gb))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97       108
           1       0.97      0.94      0.95        63

    accuracy                           0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [45]:
accuracy_score(y_test, y_pred_gb)

0.9649122807017544

In [46]:
best_model_gb.score(X_train, y_train)

1.0

In [47]:
confusion_matrix(y_test, y_pred_gb)

array([[106,   2],
       [  4,  59]])

## export

In [48]:
import pickle

In [49]:
with open('../data/modelo_logistica.pkl', 'wb') as f:
    pickle.dump(best_model_lr, f)